export const allFilteredArticles = [
  {
    id: 10492,
    rent: {
      id: 8865,
      rent_type: {
        id: 2,
        title: 'Долго',
      },
      contact_type: 0,
      title: 'Аренда помещения с Витринными окнами',
      short_description:
        'Отличное помещение под ресторан на первой линии Красногвардейского района.',
      description:
        'Помещение на первой линии проспекта с выделенной летней верандой на первой линии. Большие панорамные окна. Помещение располагается в густонаселенном жилом районе. Наличие стихийной парковки и выделенного места под летнюю террасу. Установлена и согласованна свеча. Мощность по договору  51 кВт. Два входа с фасада здания и со двора (зона погрузки)',
      payback: 0,
      price: 342000,
      price_square: 1234,
      tax: 150000,
      tax_general: 340000,
      promo_address: 'Индустриальный проспект дом 10',
      no_promo: false,
      exclusive: false,
      status: {
        id: 1,
        title: 'На сайте',
      },
      furniture: {
        id: 2,
        title: 'Нет',
      },
      equipment: {
        id: 2,
        title: 'Нет',
      },
      arendator: null,
      types: [],
    },
    sale: null,
    business_sale: null,
    images: [
      {
        id: 24142,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/2018-09-25_15-07-08.png',
        type: 1,
        hidden: true,
        is_rent: false,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10492,
      },
      {
        id: 24139,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/ewewqr.jpg',
        type: 0,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10492,
      },
      {
        id: 24140,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/sdfg.jpg',
        type: 0,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10492,
      },
      {
        id: 24141,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/wqer.jpg',
        type: 0,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10492,
      },
    ],
    processed: false,
    object_num: null,
    wcafe: '',
    actual_date: '2018-09-25T12:36:29Z',
    datetime_created: '2018-09-25T12:36:29Z',
    datetime_updated: '2018-09-25T12:36:29Z',
    address_num: null,
    is_supergo: false,
    is_goodview: false,
    district_hidden: false,
    title: 'Васаби',
    is_open: true,
    scheduling_start: 24,
    scheduling_end: null,
    square: 277.0,
    square_kitchen: null,
    square_room: null,
    square_1: null,
    square_2: null,
    square_3: null,
    square_4: null,
    square_5: null,
    power: 51,
    has_gas: false,
    ceil_height: 3.1,
    deep_of_floor: null,
    deleted: false,
    promo_address: 'Индустриальный проспект 10',
    no_promo: false,
    video_link: null,
    location: {
      id: 3,
      title: 'Торговый центр',
    },
    owner: null,
    owner_busines: null,
    district: {
      id: 7,
      title: 'Красногвардейский',
      is_center: false,
      is_south: false,
      is_north: true,
    },
    floor: {
      id: 1,
      number: 1,
      title: 'Первый этаж',
    },
    entrance: {
      id: 1,
      title: 'Первая линия',
    },
    format: [
      {
        id: 3,
        title: 'Ресторан',
      },
    ],
    types: [
      {
        id: 2,
        title: 'Вытяжка',
        only_for_purchase: true,
      },
      {
        id: 4,
        title: 'Улица',
        only_for_purchase: true,
      },
      {
        id: 14,
        title: 'Витринные окна',
        only_for_purchase: true,
      },
    ],
  },
  {
    id: 10493,
    rent: {
      id: 8866,
      rent_type: {
        id: 2,
        title: 'Долго',
      },
      contact_type: 0,
      title: 'Торговое помещение 40м',
      short_description:
        'Отличное помещение с витринными окнами и входом с Левашовского проспекта',
      description:
        'Отличное помещение с витринными окнами и входом с Левашовского проспекта , хорошая проходимость, 2 мин от метро Петроградская, по соседству ателье и магазин одежды. Много лет - магазин цветы. Закрывается по семейным обстоятельствам. Под промтовары( не продукты!) Срочно сдается!!',
      payback: 0,
      price: 85000,
      price_square: 2125,
      tax: 42500,
      tax_general: 42500,
      promo_address: '',
      no_promo: true,
      exclusive: false,
      status: {
        id: 1,
        title: 'На сайте',
      },
      furniture: {
        id: 2,
        title: 'Нет',
      },
      equipment: {
        id: 2,
        title: 'Нет',
      },
      arendator: null,
      types: [],
    },
    sale: null,
    business_sale: null,
    images: [
      {
        id: 24144,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/4795786128.jpg',
        type: 1,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10493,
      },
      {
        id: 24145,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/4795786630.jpg',
        type: 1,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10493,
      },
      {
        id: 24146,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/4795786906.jpg',
        type: 1,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10493,
      },
    ],
    processed: false,
    object_num: null,
    wcafe: '',
    actual_date: '2018-09-26T09:54:05Z',
    datetime_created: '2018-09-26T09:49:05Z',
    datetime_updated: '2018-09-26T09:54:05Z',
    address_num: null,
    is_supergo: false,
    is_goodview: false,
    district_hidden: false,
    title: 'Магазин Цветов/подарков',
    is_open: false,
    scheduling_start: null,
    scheduling_end: null,
    square: 40.0,
    square_kitchen: null,
    square_room: null,
    square_1: null,
    square_2: null,
    square_3: null,
    square_4: null,
    square_5: null,
    power: 5,
    has_gas: false,
    ceil_height: 2.7,
    deep_of_floor: null,
    deleted: false,
    promo_address: null,
    no_promo: true,
    video_link: null,
    location: {
      id: 3,
      title: 'Торговый центр',
    },
    owner: null,
    owner_busines: null,
    district: {
      id: 13,
      title: 'Петроградский',
      is_center: false,
      is_south: false,
      is_north: true,
    },
    floor: {
      id: 1,
      number: 1,
      title: 'Первый этаж',
    },
    entrance: {
      id: 1,
      title: 'Первая линия',
    },
    format: [
      {
        id: 13,
        title: 'Торговое помещение',
      },
    ],
    types: [
      {
        id: 4,
        title: 'Улица',
        only_for_purchase: true,
      },
    ],
  },
  {
    id: 10494,
    rent: {
      id: 8867,
      rent_type: {
        id: 2,
        title: 'Долго',
      },
      contact_type: 0,
      title: 'Помещение свободного назначения, 50 м²',
      short_description:
        'Сдается в аренду отличное помещение в Калининском районе, в 3 минутах ходьбы от Финляндского вокзала и станции метро "Площадь Ленина". Пешеходный переход. Общая площадь 50 кв.М.',
      description:
        'Сдается в аренду отличное помещение в Калининском районе, в 3 минутах ходьбы от Финляндского вокзала и станции метро "Площадь Ленина". Пешеходный переход. Общая площадь 50 кв.М. Помещение расположено на первом этаже, имеет отдельный вход с Лесного проспекта, 4 витринных окна, энергетическая мощность 20 кВт, приточно-вытяжная вентиляция, качественный ремонт, высота потолков 3,5 м. Рядом с помещением Военно -медицинская Академия,крупные банки и бизнес-центры,дворец культуры «Выборгский». \nОтличное место, чтобы открыть: булочки\\ хлеб\\ шаверму\\ суши\\ бургерную и т.Д. \nКолоссальный транспортный и пешеходный трафик. Просмотр в удобное время!',
      payback: 0,
      price: 95000,
      price_square: 1900,
      tax: 47500,
      tax_general: 47500,
      promo_address: '',
      no_promo: true,
      exclusive: false,
      status: {
        id: 1,
        title: 'На сайте',
      },
      furniture: {
        id: 2,
        title: 'Нет',
      },
      equipment: {
        id: 2,
        title: 'Нет',
      },
      arendator: null,
      types: [],
    },
    sale: null,
    business_sale: null,
    images: [
      {
        id: 24148,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/4563641668.jpg',
        type: 1,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10494,
      },
      {
        id: 24149,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/4563641997.jpg',
        type: 1,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10494,
      },
      {
        id: 24150,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/4563642512.jpg',
        type: 1,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10494,
      },
      {
        id: 24147,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/4563643077.jpg',
        type: 0,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10494,
      },
    ],
    processed: false,
    object_num: null,
    wcafe: '',
    actual_date: '2018-09-26T09:57:13Z',
    datetime_created: '2018-09-26T09:57:13Z',
    datetime_updated: '2018-09-26T09:57:13Z',
    address_num: null,
    is_supergo: false,
    is_goodview: false,
    district_hidden: false,
    title: 'Суши Вок',
    is_open: false,
    scheduling_start: null,
    scheduling_end: null,
    square: 50.0,
    square_kitchen: null,
    square_room: null,
    square_1: null,
    square_2: null,
    square_3: null,
    square_4: null,
    square_5: null,
    power: 20,
    has_gas: false,
    ceil_height: 3.5,
    deep_of_floor: null,
    deleted: false,
    promo_address: null,
    no_promo: true,
    video_link: null,
    location: {
      id: 4,
      title: 'ОСЗ',
    },
    owner: null,
    owner_busines: null,
    district: {
      id: 4,
      title: 'Калининский',
      is_center: false,
      is_south: false,
      is_north: true,
    },
    floor: {
      id: 1,
      number: 1,
      title: 'Первый этаж',
    },
    entrance: null,
    format: [
      {
        id: 2,
        title: 'Кафе',
      },
      {
        id: 3,
        title: 'Ресторан',
      },
      {
        id: 4,
        title: 'Столовая',
      },
      {
        id: 5,
        title: 'Фаст-Фуд',
      },
    ],
    types: [
      {
        id: 4,
        title: 'Улица',
        only_for_purchase: true,
      },
    ],
  },
  {
    id: 10496,
    rent: {
      id: 8868,
      rent_type: {
        id: 2,
        title: 'Долго',
      },
      contact_type: 0,
      title: 'Аренда помещения в Центральном районе',
      short_description: 'Первый этаж\nБольшие окна\nОтличный трафик',
      description:
        'Аренда помещения в Центральном районе на отличном трафике  \nПомещение с хорошей планировкой\nВдоль фасада идут большие окна\nПомещение имеет отдельный вход с улицы и выход во двор\nРанее располагалась торговля\nОбщая площадь - 190 м2, потолки - 3.6 метра\nПодведены все необходимые коммуникации\nВыделенная электрическая мощность - 45 кВт\nВозможна установка приточно-вытяжной вентиляции\nС арендатором заключается долгосрочный договор\n\nАрендная ставка - 500 000 рублей\nКоммунальные услуги оплачиваются отдельно\nКомиссия - 250 000 рублей',
      payback: 0,
      price: 500000,
      price_square: 2631,
      tax: 250000,
      tax_general: 250000,
      promo_address: '',
      no_promo: true,
      exclusive: false,
      status: {
        id: 1,
        title: 'На сайте',
      },
      furniture: {
        id: 2,
        title: 'Нет',
      },
      equipment: {
        id: 2,
        title: 'Нет',
      },
      arendator: null,
      types: [],
    },
    sale: null,
    business_sale: null,
    images: [
      {
        id: 24158,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/fasad_B4t0NQG.jpg',
        type: 1,
        hidden: false,
        is_rent: false,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10496,
      },
      {
        id: 24208,
        position: null,
        image:
          'http://api.worldcafe.ru/media/photo/glweizvgeskh2s5fhlhxx6jpwhgtrafj.jpg',
        type: 0,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10496,
      },
      {
        id: 24209,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/1222112211.jpg',
        type: 0,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10496,
      },
      {
        id: 24210,
        position: null,
        image:
          'http://api.worldcafe.ru/media/photo/32583088_7XPeqvONFDRPJCmUK2Xu_2xUP9-XFY_9kUWA2y0mLOw.jpg',
        type: 0,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10496,
      },
    ],
    processed: true,
    object_num: null,
    wcafe: '',
    actual_date: '2018-10-01T16:57:03Z',
    datetime_created: '2018-09-26T13:43:26Z',
    datetime_updated: '2018-10-01T16:57:03Z',
    address_num: '22',
    is_supergo: false,
    is_goodview: false,
    district_hidden: false,
    title: 'Аптека Радуга',
    is_open: false,
    scheduling_start: null,
    scheduling_end: null,
    square: 190.0,
    square_kitchen: null,
    square_room: null,
    square_1: null,
    square_2: null,
    square_3: null,
    square_4: null,
    square_5: null,
    power: 45,
    has_gas: false,
    ceil_height: 3.6,
    deep_of_floor: null,
    deleted: false,
    promo_address: 'улица Маяковского, д.19/15',
    no_promo: false,
    video_link: null,
    location: {
      id: 3,
      title: 'Торговый центр',
    },
    owner: null,
    owner_busines: null,
    district: {
      id: 18,
      title: 'Центральный',
      is_center: true,
      is_south: false,
      is_north: false,
    },
    floor: {
      id: 1,
      number: 1,
      title: 'Первый этаж',
    },
    entrance: null,
    format: [
      {
        id: 13,
        title: 'Торговое помещение',
      },
    ],
    types: [
      {
        id: 4,
        title: 'Улица',
        only_for_purchase: true,
      },
      {
        id: 14,
        title: 'Витринные окна',
        only_for_purchase: true,
      },
    ],
  },
  {
    id: 10497,
    rent: {
      id: 8869,
      rent_type: {
        id: 2,
        title: 'Долго',
      },
      contact_type: 0,
      title: 'Кафе на оживленной трассе у бензоколонки Shell',
      short_description:
        'Кафе на оживленной трассе у бензоколонки Shell по дороге на Игору',
      description:
        'Предлагается в аренду кафе, расположенное на 11-м километре Новоприозерского шоссе, рядом с заправкой Shell, на пересечении оживленных трасс, в непосредственной близости от транспортной развязки.\n<br/><br/>\nВокруг несколько новых элитных коттеджных поселков. Огромный автомобильный трафик, в том числе и туристический (дорога на Игору).\n<br/><br/>\nОтдельно-стоящее здание. Хороший ремонт. Своя скважина, бойлеры. Приличный контингент. Без оборудования и мебели.\n<br/><br/>\nАрендная ставка 50 000 руб./мес. \n<br/><br/>\nУсловия обсуждаются.\n<br/><br/>\nКомиссия 50 000 руб.',
      payback: 0,
      price: 50000,
      price_square: 625,
      tax: 50000,
      tax_general: 100000,
      promo_address: '11 км Новоприозерское шоссе',
      no_promo: false,
      exclusive: false,
      status: {
        id: 1,
        title: 'На сайте',
      },
      furniture: {
        id: 2,
        title: 'Нет',
      },
      equipment: {
        id: 2,
        title: 'Нет',
      },
      arendator: null,
      types: [],
    },
    sale: null,
    business_sale: null,
    images: [
      {
        id: 24166,
        position: null,
        image:
          'http://api.worldcafe.ru/media/photo/6a255ead-0bd8-469d-85d7-13ba2f180ed4_niH2Juj.jpg',
        type: 1,
        hidden: false,
        is_rent: false,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10497,
      },
      {
        id: 24167,
        position: null,
        image:
          'http://api.worldcafe.ru/media/photo/60a3c6a0-94d9-4cbe-83bb-ddc8a55adb30_Q13gCSy.jpg',
        type: 1,
        hidden: false,
        is_rent: false,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10497,
      },
      {
        id: 24160,
        position: null,
        image:
          'http://api.worldcafe.ru/media/photo/5adb89c9-926e-4d48-91ac-9699733acacf.jpg',
        type: 0,
        hidden: false,
        is_rent: false,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10497,
      },
      {
        id: 24162,
        position: null,
        image:
          'http://api.worldcafe.ru/media/photo/36b05cfb-cccc-4360-988e-78e25d73fe1c.jpg',
        type: 0,
        hidden: false,
        is_rent: false,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10497,
      },
      {
        id: 24164,
        position: null,
        image:
          'http://api.worldcafe.ru/media/photo/904f9b35-8010-4e79-8d0a-e25e943c441f.jpg',
        type: 0,
        hidden: false,
        is_rent: false,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10497,
      },
      {
        id: 24165,
        position: null,
        image:
          'http://api.worldcafe.ru/media/photo/5a20a3e4-98b7-4649-a57e-85543fb17735.jpg',
        type: 0,
        hidden: false,
        is_rent: false,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10497,
      },
    ],
    processed: false,
    object_num: null,
    wcafe: '',
    actual_date: '2018-09-26T15:24:57Z',
    datetime_created: '2018-09-26T14:44:46Z',
    datetime_updated: '2018-09-26T15:24:57Z',
    address_num: null,
    is_supergo: false,
    is_goodview: false,
    district_hidden: false,
    title: 'Придорожное кафе',
    is_open: false,
    scheduling_start: null,
    scheduling_end: null,
    square: 80.0,
    square_kitchen: null,
    square_room: null,
    square_1: null,
    square_2: null,
    square_3: null,
    square_4: null,
    square_5: null,
    power: 30,
    has_gas: false,
    ceil_height: null,
    deep_of_floor: null,
    deleted: false,
    promo_address: 'Новоприозерское шоссе 11-й километр',
    no_promo: false,
    video_link: null,
    location: {
      id: 4,
      title: 'ОСЗ',
    },
    owner: {
      id: 4831,
      email: '',
      phone: '+79112195558',
      first_name: 'Игорь',
      last_name: '',
      patronim: '',
      info: 'Whatsapp по этому номеру',
      company: '',
      image: null,
    },
    owner_busines: null,
    district: {
      id: 19,
      title: 'Всеволожский',
      is_center: false,
      is_south: false,
      is_north: true,
    },
    floor: {
      id: 1,
      number: 1,
      title: 'Первый этаж',
    },
    entrance: {
      id: 1,
      title: 'Первая линия',
    },
    format: [
      {
        id: 2,
        title: 'Кафе',
      },
    ],
    types: [
      {
        id: 2,
        title: 'Вытяжка',
        only_for_purchase: true,
      },
      {
        id: 3,
        title: 'Громкая музыка ночью',
        only_for_purchase: true,
      },
      {
        id: 4,
        title: 'Улица',
        only_for_purchase: true,
      },
      {
        id: 5,
        title: 'ОСЗ',
        only_for_purchase: true,
      },
      {
        id: 14,
        title: 'Витринные окна',
        only_for_purchase: true,
      },
    ],
  },
  {
    id: 10498,
    rent: {
      id: 8870,
      rent_type: {
        id: 2,
        title: 'Долго',
      },
      contact_type: 0,
      title: 'Помещение свободного назначения, 55 м²',
      short_description:
        'Помещение 55м2. Сделан хороший ремонт. Мощность 15 квт . Вход с ул. Котовского . Витринные',
      description:
        'Помещение 55м2. Сделан хороший ремонт. Мощность 15 квт . Вход с ул. Котовского . Витринные. Подойдет под любой вид деятельности.',
      payback: 0,
      price: 82500,
      price_square: 1500,
      tax: 41250,
      tax_general: 82500,
      promo_address: 'Улица Мира',
      no_promo: false,
      exclusive: false,
      status: {
        id: 1,
        title: 'На сайте',
      },
      furniture: {
        id: 2,
        title: 'Нет',
      },
      equipment: {
        id: 2,
        title: 'Нет',
      },
      arendator: null,
      types: [],
    },
    sale: null,
    business_sale: null,
    images: [
      {
        id: 24170,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/1ism.jpg',
        type: 1,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10498,
      },
      {
        id: 24171,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/2ism.jpg',
        type: 1,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10498,
      },
      {
        id: 24168,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/4807136074.jpg',
        type: 0,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10498,
      },
      {
        id: 24169,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/4807136899.jpg',
        type: 0,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10498,
      },
    ],
    processed: false,
    object_num: null,
    wcafe: '',
    actual_date: '2018-09-27T08:34:33Z',
    datetime_created: '2018-09-27T08:34:33Z',
    datetime_updated: '2018-09-27T08:34:33Z',
    address_num: null,
    is_supergo: false,
    is_goodview: false,
    district_hidden: false,
    title: 'Новое помещение',
    is_open: false,
    scheduling_start: null,
    scheduling_end: null,
    square: 55.0,
    square_kitchen: null,
    square_room: null,
    square_1: null,
    square_2: null,
    square_3: null,
    square_4: null,
    square_5: null,
    power: 15,
    has_gas: false,
    ceil_height: 3.5,
    deep_of_floor: null,
    deleted: false,
    promo_address: 'Улица Мира',
    no_promo: false,
    video_link: null,
    location: {
      id: 3,
      title: 'Торговый центр',
    },
    owner: null,
    owner_busines: null,
    district: {
      id: 13,
      title: 'Петроградский',
      is_center: false,
      is_south: false,
      is_north: true,
    },
    floor: {
      id: 1,
      number: 1,
      title: 'Первый этаж',
    },
    entrance: {
      id: 1,
      title: 'Первая линия',
    },
    format: [
      {
        id: 27,
        title: 'Раньше ничего не было',
      },
    ],
    types: [
      {
        id: 4,
        title: 'Улица',
        only_for_purchase: true,
      },
      {
        id: 14,
        title: 'Витринные окна',
        only_for_purchase: true,
      },
    ],
  },
  {
    id: 10499,
    rent: {
      id: 8872,
      rent_type: {
        id: 2,
        title: 'Долго',
      },
      contact_type: 0,
      title: 'Помещение свободного назначения, 100 м²',
      short_description: 'Сдается помещение свободного назначения.',
      description:
        'Сдается помещение свободного назначения.\nИмеется:\n1. 32 кВт\n2. Два входа (парадный и черный под разгрузку-погрузку)\n3. Большое фасадное остекление\n4. Вентиляция с выходом на крышу.\n5. Зал 50м2 с гостевым туалетом\nпод кафе, производство пиццы, суши и т.Д.\nдоговор на 11 месяцев с дальнейшей с пролонгацией!',
      payback: 0,
      price: 120000,
      price_square: 1200,
      tax: 60000,
      tax_general: 120000,
      promo_address: '',
      no_promo: true,
      exclusive: false,
      status: {
        id: 1,
        title: 'На сайте',
      },
      furniture: {
        id: 2,
        title: 'Нет',
      },
      equipment: {
        id: 2,
        title: 'Нет',
      },
      arendator: null,
      types: [],
    },
    sale: null,
    business_sale: null,
    images: [
      {
        id: 24180,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/4807103443.jpg',
        type: 1,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10499,
      },
    ],
    processed: false,
    object_num: null,
    wcafe: '',
    actual_date: '2018-09-28T05:50:11Z',
    datetime_created: '2018-09-28T05:50:11Z',
    datetime_updated: '2018-09-28T05:50:11Z',
    address_num: null,
    is_supergo: false,
    is_goodview: false,
    district_hidden: false,
    title: 'Кафе',
    is_open: false,
    scheduling_start: null,
    scheduling_end: null,
    square: 100.0,
    square_kitchen: null,
    square_room: null,
    square_1: null,
    square_2: null,
    square_3: null,
    square_4: null,
    square_5: null,
    power: 32,
    has_gas: false,
    ceil_height: 3.2,
    deep_of_floor: null,
    deleted: false,
    promo_address: null,
    no_promo: true,
    video_link: null,
    location: null,
    owner: null,
    owner_busines: null,
    district: {
      id: 17,
      title: 'Фрунзенский',
      is_center: false,
      is_south: true,
      is_north: false,
    },
    floor: {
      id: 1,
      number: 1,
      title: 'Первый этаж',
    },
    entrance: null,
    format: [
      {
        id: 11,
        title: 'Кальянная',
      },
    ],
    types: [
      {
        id: 2,
        title: 'Вытяжка',
        only_for_purchase: true,
      },
      {
        id: 4,
        title: 'Улица',
        only_for_purchase: true,
      },
    ],
  },
]

export const singleArticleList = {
  10492: {
    id: 10492,
    rent: {
      id: 8865,
      rent_type: {
        id: 2,
        title: 'Долго',
      },
      contact_type: 0,
      title: 'Аренда помещения с Витринными окнами',
      short_description:
        'Отличное помещение под ресторан на первой линии Красногвардейского района.',
      description:
        'Помещение на первой линии проспекта с выделенной летней верандой на первой линии. Большие панорамные окна. Помещение располагается в густонаселенном жилом районе. Наличие стихийной парковки и выделенного места под летнюю террасу. Установлена и согласованна свеча. Мощность по договору  51 кВт. Два входа с фасада здания и со двора (зона погрузки)',
      payback: 0,
      price: 342000,
      price_square: 1234,
      tax: 150000,
      tax_general: 340000,
      promo_address: 'Индустриальный проспект дом 10',
      no_promo: false,
      exclusive: false,
      status: {
        id: 1,
        title: 'На сайте',
      },
      furniture: {
        id: 2,
        title: 'Нет',
      },
      equipment: {
        id: 2,
        title: 'Нет',
      },
      arendator: null,
      types: [],
    },
    sale: null,
    business_sale: null,
    images: [
      {
        id: 24142,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/2018-09-25_15-07-08.png',
        type: 1,
        hidden: true,
        is_rent: false,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10492,
      },
      {
        id: 24139,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/ewewqr.jpg',
        type: 0,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10492,
      },
      {
        id: 24140,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/sdfg.jpg',
        type: 0,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10492,
      },
      {
        id: 24141,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/wqer.jpg',
        type: 0,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10492,
      },
    ],
    processed: false,
    object_num: null,
    wcafe: '',
    actual_date: '2018-09-25T12:36:29Z',
    datetime_created: '2018-09-25T12:36:29Z',
    datetime_updated: '2018-09-25T12:36:29Z',
    address_num: null,
    is_supergo: false,
    is_goodview: false,
    district_hidden: false,
    title: 'Васаби',
    is_open: true,
    scheduling_start: 24,
    scheduling_end: null,
    square: 277.0,
    square_kitchen: null,
    square_room: null,
    square_1: null,
    square_2: null,
    square_3: null,
    square_4: null,
    square_5: null,
    power: 51,
    has_gas: false,
    ceil_height: 3.1,
    deep_of_floor: null,
    deleted: false,
    promo_address: 'Индустриальный проспект 10',
    no_promo: false,
    video_link: null,
    location: {
      id: 3,
      title: 'Торговый центр',
    },
    owner: null,
    owner_busines: null,
    district: {
      id: 7,
      title: 'Красногвардейский',
      is_center: false,
      is_south: false,
      is_north: true,
    },
    floor: {
      id: 1,
      number: 1,
      title: 'Первый этаж',
    },
    entrance: {
      id: 1,
      title: 'Первая линия',
    },
    format: [
      {
        id: 3,
        title: 'Ресторан',
      },
    ],
    types: [
      {
        id: 2,
        title: 'Вытяжка',
        only_for_purchase: true,
      },
      {
        id: 4,
        title: 'Улица',
        only_for_purchase: true,
      },
      {
        id: 14,
        title: 'Витринные окна',
        only_for_purchase: true,
      },
    ],
  },
  10494: {
    id: 10494,
    rent: {
      id: 8867,
      rent_type: {
        id: 2,
        title: 'Долго',
      },
      contact_type: 0,
      title: 'Помещение свободного назначения, 50 м²',
      short_description:
        'Сдается в аренду отличное помещение в Калининском районе, в 3 минутах ходьбы от Финляндского вокзала и станции метро "Площадь Ленина". Пешеходный переход. Общая площадь 50 кв.М.',
      description:
        'Сдается в аренду отличное помещение в Калининском районе, в 3 минутах ходьбы от Финляндского вокзала и станции метро "Площадь Ленина". Пешеходный переход. Общая площадь 50 кв.М. Помещение расположено на первом этаже, имеет отдельный вход с Лесного проспекта, 4 витринных окна, энергетическая мощность 20 кВт, приточно-вытяжная вентиляция, качественный ремонт, высота потолков 3,5 м. Рядом с помещением Военно -медицинская Академия,крупные банки и бизнес-центры,дворец культуры «Выборгский». \nОтличное место, чтобы открыть: булочки\\ хлеб\\ шаверму\\ суши\\ бургерную и т.Д. \nКолоссальный транспортный и пешеходный трафик. Просмотр в удобное время!',
      payback: 0,
      price: 95000,
      price_square: 1900,
      tax: 47500,
      tax_general: 47500,
      promo_address: '',
      no_promo: true,
      exclusive: false,
      status: {
        id: 1,
        title: 'На сайте',
      },
      furniture: {
        id: 2,
        title: 'Нет',
      },
      equipment: {
        id: 2,
        title: 'Нет',
      },
      arendator: null,
      types: [],
    },
    sale: null,
    business_sale: null,
    images: [
      {
        id: 24148,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/4563641668.jpg',
        type: 1,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10494,
      },
      {
        id: 24149,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/4563641997.jpg',
        type: 1,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10494,
      },
      {
        id: 24150,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/4563642512.jpg',
        type: 1,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10494,
      },
      {
        id: 24147,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/4563643077.jpg',
        type: 0,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10494,
      },
    ],
    processed: false,
    object_num: null,
    wcafe: '',
    actual_date: '2018-09-26T09:57:13Z',
    datetime_created: '2018-09-26T09:57:13Z',
    datetime_updated: '2018-09-26T09:57:13Z',
    address_num: null,
    is_supergo: false,
    is_goodview: false,
    district_hidden: false,
    title: 'Суши Вок',
    is_open: false,
    scheduling_start: null,
    scheduling_end: null,
    square: 50.0,
    square_kitchen: null,
    square_room: null,
    square_1: null,
    square_2: null,
    square_3: null,
    square_4: null,
    square_5: null,
    power: 20,
    has_gas: false,
    ceil_height: 3.5,
    deep_of_floor: null,
    deleted: false,
    promo_address: null,
    no_promo: true,
    video_link: null,
    location: {
      id: 4,
      title: 'ОСЗ',
    },
    owner: null,
    owner_busines: null,
    district: {
      id: 4,
      title: 'Калининский',
      is_center: false,
      is_south: false,
      is_north: true,
    },
    floor: {
      id: 1,
      number: 1,
      title: 'Первый этаж',
    },
    entrance: null,
    format: [
      {
        id: 2,
        title: 'Кафе',
      },
      {
        id: 3,
        title: 'Ресторан',
      },
      {
        id: 4,
        title: 'Столовая',
      },
      {
        id: 5,
        title: 'Фаст-Фуд',
      },
    ],
    types: [
      {
        id: 4,
        title: 'Улица',
        only_for_purchase: true,
      },
    ],
  },
  10496: {
    id: 10496,
    rent: {
      id: 8868,
      rent_type: {
        id: 2,
        title: 'Долго',
      },
      contact_type: 0,
      title: 'Аренда помещения в Центральном районе',
      short_description: 'Первый этаж\nБольшие окна\nОтличный трафик',
      description:
        'Аренда помещения в Центральном районе на отличном трафике  \nПомещение с хорошей планировкой\nВдоль фасада идут большие окна\nПомещение имеет отдельный вход с улицы и выход во двор\nРанее располагалась торговля\nОбщая площадь - 190 м2, потолки - 3.6 метра\nПодведены все необходимые коммуникации\nВыделенная электрическая мощность - 45 кВт\nВозможна установка приточно-вытяжной вентиляции\nС арендатором заключается долгосрочный договор\n\nАрендная ставка - 500 000 рублей\nКоммунальные услуги оплачиваются отдельно\nКомиссия - 250 000 рублей',
      payback: 0,
      price: 500000,
      price_square: 2631,
      tax: 250000,
      tax_general: 250000,
      promo_address: '',
      no_promo: true,
      exclusive: false,
      status: {
        id: 1,
        title: 'На сайте',
      },
      furniture: {
        id: 2,
        title: 'Нет',
      },
      equipment: {
        id: 2,
        title: 'Нет',
      },
      arendator: null,
      types: [],
    },
    sale: null,
    business_sale: null,
    images: [
      {
        id: 24158,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/fasad_B4t0NQG.jpg',
        type: 1,
        hidden: false,
        is_rent: false,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10496,
      },
      {
        id: 24208,
        position: null,
        image:
          'http://api.worldcafe.ru/media/photo/glweizvgeskh2s5fhlhxx6jpwhgtrafj.jpg',
        type: 0,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10496,
      },
      {
        id: 24209,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/1222112211.jpg',
        type: 0,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10496,
      },
      {
        id: 24210,
        position: null,
        image:
          'http://api.worldcafe.ru/media/photo/32583088_7XPeqvONFDRPJCmUK2Xu_2xUP9-XFY_9kUWA2y0mLOw.jpg',
        type: 0,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10496,
      },
    ],
    processed: true,
    object_num: null,
    wcafe: '',
    actual_date: '2018-10-01T16:57:03Z',
    datetime_created: '2018-09-26T13:43:26Z',
    datetime_updated: '2018-10-01T16:57:03Z',
    address_num: '22',
    is_supergo: false,
    is_goodview: false,
    district_hidden: false,
    title: 'Аптека Радуга',
    is_open: false,
    scheduling_start: null,
    scheduling_end: null,
    square: 190.0,
    square_kitchen: null,
    square_room: null,
    square_1: null,
    square_2: null,
    square_3: null,
    square_4: null,
    square_5: null,
    power: 45,
    has_gas: false,
    ceil_height: 3.6,
    deep_of_floor: null,
    deleted: false,
    promo_address: 'улица Маяковского, д.19/15',
    no_promo: false,
    video_link: null,
    location: {
      id: 3,
      title: 'Торговый центр',
    },
    owner: null,
    owner_busines: null,
    district: {
      id: 18,
      title: 'Центральный',
      is_center: true,
      is_south: false,
      is_north: false,
    },
    floor: {
      id: 1,
      number: 1,
      title: 'Первый этаж',
    },
    entrance: null,
    format: [
      {
        id: 13,
        title: 'Торговое помещение',
      },
    ],
    types: [
      {
        id: 4,
        title: 'Улица',
        only_for_purchase: true,
      },
      {
        id: 14,
        title: 'Витринные окна',
        only_for_purchase: true,
      },
    ],
  },
  10497: {
    id: 10497,
    rent: {
      id: 8869,
      rent_type: {
        id: 2,
        title: 'Долго',
      },
      contact_type: 0,
      title: 'Кафе на оживленной трассе у бензоколонки Shell',
      short_description:
        'Кафе на оживленной трассе у бензоколонки Shell по дороге на Игору',
      description:
        'Предлагается в аренду кафе, расположенное на 11-м километре Новоприозерского шоссе, рядом с заправкой Shell, на пересечении оживленных трасс, в непосредственной близости от транспортной развязки.\n<br/><br/>\nВокруг несколько новых элитных коттеджных поселков. Огромный автомобильный трафик, в том числе и туристический (дорога на Игору).\n<br/><br/>\nОтдельно-стоящее здание. Хороший ремонт. Своя скважина, бойлеры. Приличный контингент. Без оборудования и мебели.\n<br/><br/>\nАрендная ставка 50 000 руб./мес. \n<br/><br/>\nУсловия обсуждаются.\n<br/><br/>\nКомиссия 50 000 руб.',
      payback: 0,
      price: 50000,
      price_square: 625,
      tax: 50000,
      tax_general: 100000,
      promo_address: '11 км Новоприозерское шоссе',
      no_promo: false,
      exclusive: false,
      status: {
        id: 1,
        title: 'На сайте',
      },
      furniture: {
        id: 2,
        title: 'Нет',
      },
      equipment: {
        id: 2,
        title: 'Нет',
      },
      arendator: null,
      types: [],
    },
    sale: null,
    business_sale: null,
    images: [
      {
        id: 24166,
        position: null,
        image:
          'http://api.worldcafe.ru/media/photo/6a255ead-0bd8-469d-85d7-13ba2f180ed4_niH2Juj.jpg',
        type: 1,
        hidden: false,
        is_rent: false,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10497,
      },
      {
        id: 24167,
        position: null,
        image:
          'http://api.worldcafe.ru/media/photo/60a3c6a0-94d9-4cbe-83bb-ddc8a55adb30_Q13gCSy.jpg',
        type: 1,
        hidden: false,
        is_rent: false,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10497,
      },
      {
        id: 24160,
        position: null,
        image:
          'http://api.worldcafe.ru/media/photo/5adb89c9-926e-4d48-91ac-9699733acacf.jpg',
        type: 0,
        hidden: false,
        is_rent: false,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10497,
      },
      {
        id: 24162,
        position: null,
        image:
          'http://api.worldcafe.ru/media/photo/36b05cfb-cccc-4360-988e-78e25d73fe1c.jpg',
        type: 0,
        hidden: false,
        is_rent: false,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10497,
      },
      {
        id: 24164,
        position: null,
        image:
          'http://api.worldcafe.ru/media/photo/904f9b35-8010-4e79-8d0a-e25e943c441f.jpg',
        type: 0,
        hidden: false,
        is_rent: false,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10497,
      },
      {
        id: 24165,
        position: null,
        image:
          'http://api.worldcafe.ru/media/photo/5a20a3e4-98b7-4649-a57e-85543fb17735.jpg',
        type: 0,
        hidden: false,
        is_rent: false,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10497,
      },
    ],
    processed: false,
    object_num: null,
    wcafe: '',
    actual_date: '2018-09-26T15:24:57Z',
    datetime_created: '2018-09-26T14:44:46Z',
    datetime_updated: '2018-09-26T15:24:57Z',
    address_num: null,
    is_supergo: false,
    is_goodview: false,
    district_hidden: false,
    title: 'Придорожное кафе',
    is_open: false,
    scheduling_start: null,
    scheduling_end: null,
    square: 80.0,
    square_kitchen: null,
    square_room: null,
    square_1: null,
    square_2: null,
    square_3: null,
    square_4: null,
    square_5: null,
    power: 30,
    has_gas: false,
    ceil_height: null,
    deep_of_floor: null,
    deleted: false,
    promo_address: 'Новоприозерское шоссе 11-й километр',
    no_promo: false,
    video_link: null,
    location: {
      id: 4,
      title: 'ОСЗ',
    },
    owner: {
      id: 4831,
      email: '',
      phone: '+79112195558',
      first_name: 'Игорь',
      last_name: '',
      patronim: '',
      info: 'Whatsapp по этому номеру',
      company: '',
      image: null,
    },
    owner_busines: null,
    district: {
      id: 19,
      title: 'Всеволожский',
      is_center: false,
      is_south: false,
      is_north: true,
    },
    floor: {
      id: 1,
      number: 1,
      title: 'Первый этаж',
    },
    entrance: {
      id: 1,
      title: 'Первая линия',
    },
    format: [
      {
        id: 2,
        title: 'Кафе',
      },
    ],
    types: [
      {
        id: 2,
        title: 'Вытяжка',
        only_for_purchase: true,
      },
      {
        id: 3,
        title: 'Громкая музыка ночью',
        only_for_purchase: true,
      },
      {
        id: 4,
        title: 'Улица',
        only_for_purchase: true,
      },
      {
        id: 5,
        title: 'ОСЗ',
        only_for_purchase: true,
      },
      {
        id: 14,
        title: 'Витринные окна',
        only_for_purchase: true,
      },
    ],
  },
  10498: {
    id: 10498,
    rent: {
      id: 8870,
      rent_type: {
        id: 2,
        title: 'Долго',
      },
      contact_type: 0,
      title: 'Помещение свободного назначения, 55 м²',
      short_description:
        'Помещение 55м2. Сделан хороший ремонт. Мощность 15 квт . Вход с ул. Котовского . Витринные',
      description:
        'Помещение 55м2. Сделан хороший ремонт. Мощность 15 квт . Вход с ул. Котовского . Витринные. Подойдет под любой вид деятельности.',
      payback: 0,
      price: 82500,
      price_square: 1500,
      tax: 41250,
      tax_general: 82500,
      promo_address: 'Улица Мира',
      no_promo: false,
      exclusive: false,
      status: {
        id: 1,
        title: 'На сайте',
      },
      furniture: {
        id: 2,
        title: 'Нет',
      },
      equipment: {
        id: 2,
        title: 'Нет',
      },
      arendator: null,
      types: [],
    },
    sale: null,
    business_sale: null,
    images: [
      {
        id: 24170,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/1ism.jpg',
        type: 1,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10498,
      },
      {
        id: 24171,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/2ism.jpg',
        type: 1,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10498,
      },
      {
        id: 24168,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/4807136074.jpg',
        type: 0,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10498,
      },
      {
        id: 24169,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/4807136899.jpg',
        type: 0,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10498,
      },
    ],
    processed: false,
    object_num: null,
    wcafe: '',
    actual_date: '2018-09-27T08:34:33Z',
    datetime_created: '2018-09-27T08:34:33Z',
    datetime_updated: '2018-09-27T08:34:33Z',
    address_num: null,
    is_supergo: false,
    is_goodview: false,
    district_hidden: false,
    title: 'Новое помещение',
    is_open: false,
    scheduling_start: null,
    scheduling_end: null,
    square: 55.0,
    square_kitchen: null,
    square_room: null,
    square_1: null,
    square_2: null,
    square_3: null,
    square_4: null,
    square_5: null,
    power: 15,
    has_gas: false,
    ceil_height: 3.5,
    deep_of_floor: null,
    deleted: false,
    promo_address: 'Улица Мира',
    no_promo: false,
    video_link: null,
    location: {
      id: 3,
      title: 'Торговый центр',
    },
    owner: null,
    owner_busines: null,
    district: {
      id: 13,
      title: 'Петроградский',
      is_center: false,
      is_south: false,
      is_north: true,
    },
    floor: {
      id: 1,
      number: 1,
      title: 'Первый этаж',
    },
    entrance: {
      id: 1,
      title: 'Первая линия',
    },
    format: [
      {
        id: 27,
        title: 'Раньше ничего не было',
      },
    ],
    types: [
      {
        id: 4,
        title: 'Улица',
        only_for_purchase: true,
      },
      {
        id: 14,
        title: 'Витринные окна',
        only_for_purchase: true,
      },
    ],
  },
  10499: {
    id: 10499,
    rent: {
      id: 8872,
      rent_type: {
        id: 2,
        title: 'Долго',
      },
      contact_type: 0,
      title: 'Помещение свободного назначения, 100 м²',
      short_description: 'Сдается помещение свободного назначения.',
      description:
        'Сдается помещение свободного назначения.\nИмеется:\n1. 32 кВт\n2. Два входа (парадный и черный под разгрузку-погрузку)\n3. Большое фасадное остекление\n4. Вентиляция с выходом на крышу.\n5. Зал 50м2 с гостевым туалетом\nпод кафе, производство пиццы, суши и т.Д.\nдоговор на 11 месяцев с дальнейшей с пролонгацией!',
      payback: 0,
      price: 120000,
      price_square: 1200,
      tax: 60000,
      tax_general: 120000,
      promo_address: '',
      no_promo: true,
      exclusive: false,
      status: {
        id: 1,
        title: 'На сайте',
      },
      furniture: {
        id: 2,
        title: 'Нет',
      },
      equipment: {
        id: 2,
        title: 'Нет',
      },
      arendator: null,
      types: [],
    },
    sale: null,
    business_sale: null,
    images: [
      {
        id: 24180,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/4807103443.jpg',
        type: 1,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10499,
      },
    ],
    processed: false,
    object_num: null,
    wcafe: '',
    actual_date: '2018-09-28T05:50:11Z',
    datetime_created: '2018-09-28T05:50:11Z',
    datetime_updated: '2018-09-28T05:50:11Z',
    address_num: null,
    is_supergo: false,
    is_goodview: false,
    district_hidden: false,
    title: 'Кафе',
    is_open: false,
    scheduling_start: null,
    scheduling_end: null,
    square: 100.0,
    square_kitchen: null,
    square_room: null,
    square_1: null,
    square_2: null,
    square_3: null,
    square_4: null,
    square_5: null,
    power: 32,
    has_gas: false,
    ceil_height: 3.2,
    deep_of_floor: null,
    deleted: false,
    promo_address: null,
    no_promo: true,
    video_link: null,
    location: null,
    owner: null,
    owner_busines: null,
    district: {
      id: 17,
      title: 'Фрунзенский',
      is_center: false,
      is_south: true,
      is_north: false,
    },
    floor: {
      id: 1,
      number: 1,
      title: 'Первый этаж',
    },
    entrance: null,
    format: [
      {
        id: 11,
        title: 'Кальянная',
      },
    ],
    types: [
      {
        id: 2,
        title: 'Вытяжка',
        only_for_purchase: true,
      },
      {
        id: 4,
        title: 'Улица',
        only_for_purchase: true,
      },
    ],
  },
  10493: {
    id: 10493,
    rent: {
      id: 8866,
      rent_type: {
        id: 2,
        title: 'Долго',
      },
      contact_type: 0,
      title: 'Торговое помещение 40м',
      short_description:
        'Отличное помещение с витринными окнами и входом с Левашовского проспекта',
      description:
        'Отличное помещение с витринными окнами и входом с Левашовского проспекта , хорошая проходимость, 2 мин от метро Петроградская, по соседству ателье и магазин одежды. Много лет - магазин цветы. Закрывается по семейным обстоятельствам. Под промтовары( не продукты!) Срочно сдается!!',
      payback: 0,
      price: 85000,
      price_square: 2125,
      tax: 42500,
      tax_general: 42500,
      promo_address: '',
      no_promo: true,
      exclusive: false,
      status: {
        id: 1,
        title: 'На сайте',
      },
      furniture: {
        id: 2,
        title: 'Нет',
      },
      equipment: {
        id: 2,
        title: 'Нет',
      },
      arendator: null,
      types: [],
    },
    sale: null,
    business_sale: null,
    images: [
      {
        id: 24144,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/4795786128.jpg',
        type: 1,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10493,
      },
      {
        id: 24145,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/4795786630.jpg',
        type: 1,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10493,
      },
      {
        id: 24146,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/4795786906.jpg',
        type: 1,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10493,
      },
    ],
    processed: false,
    object_num: null,
    wcafe: '',
    actual_date: '2018-09-26T09:54:05Z',
    datetime_created: '2018-09-26T09:49:05Z',
    datetime_updated: '2018-09-26T09:54:05Z',
    address_num: null,
    is_supergo: false,
    is_goodview: false,
    district_hidden: false,
    title: 'Магазин Цветов/подарков',
    is_open: false,
    scheduling_start: null,
    scheduling_end: null,
    square: 40.0,
    square_kitchen: null,
    square_room: null,
    square_1: null,
    square_2: null,
    square_3: null,
    square_4: null,
    square_5: null,
    power: 5,
    has_gas: false,
    ceil_height: 2.7,
    deep_of_floor: null,
    deleted: false,
    promo_address: null,
    no_promo: true,
    video_link: null,
    location: {
      id: 3,
      title: 'Торговый центр',
    },
    owner: null,
    owner_busines: null,
    district: {
      id: 13,
      title: 'Петроградский',
      is_center: false,
      is_south: false,
      is_north: true,
    },
    floor: {
      id: 1,
      number: 1,
      title: 'Первый этаж',
    },
    entrance: {
      id: 1,
      title: 'Первая линия',
    },
    format: [
      {
        id: 13,
        title: 'Торговое помещение',
      },
    ],
    types: [
      {
        id: 4,
        title: 'Улица',
        only_for_purchase: true,
      },
    ],
  },
}

export const locationArticles = [
  {
    id: 10499,
    rent: {
      id: 8872,
      rent_type: {
        id: 2,
        title: 'Долго',
      },
      contact_type: 0,
      title: 'Помещение свободного назначения, 100 м²',
      short_description: 'Сдается помещение свободного назначения.',
      description:
        'Сдается помещение свободного назначения.\nИмеется:\n1. 32 кВт\n2. Два входа (парадный и черный под разгрузку-погрузку)\n3. Большое фасадное остекление\n4. Вентиляция с выходом на крышу.\n5. Зал 50м2 с гостевым туалетом\nпод кафе, производство пиццы, суши и т.Д.\nдоговор на 11 месяцев с дальнейшей с пролонгацией!',
      payback: 0,
      price: 120000,
      price_square: 1200,
      tax: 60000,
      tax_general: 120000,
      promo_address: '',
      no_promo: true,
      exclusive: false,
      status: {
        id: 1,
        title: 'На сайте',
      },
      furniture: {
        id: 2,
        title: 'Нет',
      },
      equipment: {
        id: 2,
        title: 'Нет',
      },
      arendator: null,
      types: [],
    },
    sale: null,
    business_sale: null,
    images: [
      {
        id: 24180,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/4807103443.jpg',
        type: 1,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10499,
      },
    ],
    processed: false,
    object_num: null,
    wcafe: '',
    actual_date: '2018-09-28T05:50:11Z',
    datetime_created: '2018-09-28T05:50:11Z',
    datetime_updated: '2018-09-28T05:50:11Z',
    address_num: null,
    is_supergo: false,
    is_goodview: false,
    district_hidden: false,
    title: 'Кафе',
    is_open: false,
    scheduling_start: null,
    scheduling_end: null,
    square: 100.0,
    square_kitchen: null,
    square_room: null,
    square_1: null,
    square_2: null,
    square_3: null,
    square_4: null,
    square_5: null,
    power: 32,
    has_gas: false,
    ceil_height: 3.2,
    deep_of_floor: null,
    deleted: false,
    promo_address: null,
    no_promo: true,
    video_link: null,
    location: null,
    owner: null,
    owner_busines: null,
    district: {
      id: 17,
      title: 'Фрунзенский',
      is_center: false,
      is_south: true,
      is_north: false,
    },
    floor: {
      id: 1,
      number: 1,
      title: 'Первый этаж',
    },
    entrance: null,
    format: [
      {
        id: 11,
        title: 'Кальянная',
      },
    ],
    types: [
      {
        id: 2,
        title: 'Вытяжка',
        only_for_purchase: true,
      },
      {
        id: 4,
        title: 'Улица',
        only_for_purchase: true,
      },
    ],
  },
  {
    id: 10493,
    rent: {
      id: 8866,
      rent_type: {
        id: 2,
        title: 'Долго',
      },
      contact_type: 0,
      title: 'Торговое помещение 40м',
      short_description:
        'Отличное помещение с витринными окнами и входом с Левашовского проспекта',
      description:
        'Отличное помещение с витринными окнами и входом с Левашовского проспекта , хорошая проходимость, 2 мин от метро Петроградская, по соседству ателье и магазин одежды. Много лет - магазин цветы. Закрывается по семейным обстоятельствам. Под промтовары( не продукты!) Срочно сдается!!',
      payback: 0,
      price: 85000,
      price_square: 2125,
      tax: 42500,
      tax_general: 42500,
      promo_address: '',
      no_promo: true,
      exclusive: false,
      status: {
        id: 1,
        title: 'На сайте',
      },
      furniture: {
        id: 2,
        title: 'Нет',
      },
      equipment: {
        id: 2,
        title: 'Нет',
      },
      arendator: null,
      types: [],
    },
    sale: null,
    business_sale: null,
    images: [
      {
        id: 24144,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/4795786128.jpg',
        type: 1,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10493,
      },
      {
        id: 24145,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/4795786630.jpg',
        type: 1,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10493,
      },
      {
        id: 24146,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/4795786906.jpg',
        type: 1,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10493,
      },
    ],
    processed: false,
    object_num: null,
    wcafe: '',
    actual_date: '2018-09-26T09:54:05Z',
    datetime_created: '2018-09-26T09:49:05Z',
    datetime_updated: '2018-09-26T09:54:05Z',
    address_num: null,
    is_supergo: false,
    is_goodview: false,
    district_hidden: false,
    title: 'Магазин Цветов/подарков',
    is_open: false,
    scheduling_start: null,
    scheduling_end: null,
    square: 40.0,
    square_kitchen: null,
    square_room: null,
    square_1: null,
    square_2: null,
    square_3: null,
    square_4: null,
    square_5: null,
    power: 5,
    has_gas: false,
    ceil_height: 2.7,
    deep_of_floor: null,
    deleted: false,
    promo_address: null,
    no_promo: true,
    video_link: null,
    location: {
      id: 3,
      title: 'Торговый центр',
    },
    owner: null,
    owner_busines: null,
    district: {
      id: 13,
      title: 'Петроградский',
      is_center: false,
      is_south: false,
      is_north: true,
    },
    floor: {
      id: 1,
      number: 1,
      title: 'Первый этаж',
    },
    entrance: {
      id: 1,
      title: 'Первая линия',
    },
    format: [
      {
        id: 13,
        title: 'Торговое помещение',
      },
    ],
    types: [
      {
        id: 4,
        title: 'Улица',
        only_for_purchase: true,
      },
    ],
  },
  {
    id: 10492,
    rent: {
      id: 8865,
      rent_type: {
        id: 2,
        title: 'Долго',
      },
      contact_type: 0,
      title: 'Аренда помещения с Витринными окнами',
      short_description:
        'Отличное помещение под ресторан на первой линии Красногвардейского района.',
      description:
        'Помещение на первой линии проспекта с выделенной летней верандой на первой линии. Большие панорамные окна. Помещение располагается в густонаселенном жилом районе. Наличие стихийной парковки и выделенного места под летнюю террасу. Установлена и согласованна свеча. Мощность по договору  51 кВт. Два входа с фасада здания и со двора (зона погрузки)',
      payback: 0,
      price: 342000,
      price_square: 1234,
      tax: 150000,
      tax_general: 340000,
      promo_address: 'Индустриальный проспект дом 10',
      no_promo: false,
      exclusive: false,
      status: {
        id: 1,
        title: 'На сайте',
      },
      furniture: {
        id: 2,
        title: 'Нет',
      },
      equipment: {
        id: 2,
        title: 'Нет',
      },
      arendator: null,
      types: [],
    },
    sale: null,
    business_sale: null,
    images: [
      {
        id: 24142,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/2018-09-25_15-07-08.png',
        type: 1,
        hidden: true,
        is_rent: false,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10492,
      },
      {
        id: 24139,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/ewewqr.jpg',
        type: 0,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10492,
      },
      {
        id: 24140,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/sdfg.jpg',
        type: 0,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10492,
      },
      {
        id: 24141,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/wqer.jpg',
        type: 0,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10492,
      },
    ],
    processed: false,
    object_num: null,
    wcafe: '',
    actual_date: '2018-09-25T12:36:29Z',
    datetime_created: '2018-09-25T12:36:29Z',
    datetime_updated: '2018-09-25T12:36:29Z',
    address_num: null,
    is_supergo: false,
    is_goodview: false,
    district_hidden: false,
    title: 'Васаби',
    is_open: true,
    scheduling_start: 24,
    scheduling_end: null,
    square: 277.0,
    square_kitchen: null,
    square_room: null,
    square_1: null,
    square_2: null,
    square_3: null,
    square_4: null,
    square_5: null,
    power: 51,
    has_gas: false,
    ceil_height: 3.1,
    deep_of_floor: null,
    deleted: false,
    promo_address: 'Индустриальный проспект 10',
    no_promo: false,
    video_link: null,
    location: {
      id: 3,
      title: 'Торговый центр',
    },
    owner: null,
    owner_busines: null,
    district: {
      id: 7,
      title: 'Красногвардейский',
      is_center: false,
      is_south: false,
      is_north: true,
    },
    floor: {
      id: 1,
      number: 1,
      title: 'Первый этаж',
    },
    entrance: {
      id: 1,
      title: 'Первая линия',
    },
    format: [
      {
        id: 3,
        title: 'Ресторан',
      },
    ],
    types: [
      {
        id: 2,
        title: 'Вытяжка',
        only_for_purchase: true,
      },
      {
        id: 4,
        title: 'Улица',
        only_for_purchase: true,
      },
      {
        id: 14,
        title: 'Витринные окна',
        only_for_purchase: true,
      },
    ],
  },
]

export const typeArticles = [
  {
    id: 10498,
    rent: {
      id: 8870,
      rent_type: {
        id: 2,
        title: 'Долго',
      },
      contact_type: 0,
      title: 'Помещение свободного назначения, 55 м²',
      short_description:
        'Помещение 55м2. Сделан хороший ремонт. Мощность 15 квт . Вход с ул. Котовского . Витринные',
      description:
        'Помещение 55м2. Сделан хороший ремонт. Мощность 15 квт . Вход с ул. Котовского . Витринные. Подойдет под любой вид деятельности.',
      payback: 0,
      price: 82500,
      price_square: 1500,
      tax: 41250,
      tax_general: 82500,
      promo_address: 'Улица Мира',
      no_promo: false,
      exclusive: false,
      status: {
        id: 1,
        title: 'На сайте',
      },
      furniture: {
        id: 2,
        title: 'Нет',
      },
      equipment: {
        id: 2,
        title: 'Нет',
      },
      arendator: null,
      types: [],
    },
    sale: null,
    business_sale: null,
    images: [
      {
        id: 24170,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/1ism.jpg',
        type: 1,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10498,
      },
      {
        id: 24171,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/2ism.jpg',
        type: 1,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10498,
      },
      {
        id: 24168,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/4807136074.jpg',
        type: 0,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10498,
      },
      {
        id: 24169,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/4807136899.jpg',
        type: 0,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10498,
      },
    ],
    processed: false,
    object_num: null,
    wcafe: '',
    actual_date: '2018-09-27T08:34:33Z',
    datetime_created: '2018-09-27T08:34:33Z',
    datetime_updated: '2018-09-27T08:34:33Z',
    address_num: null,
    is_supergo: false,
    is_goodview: false,
    district_hidden: false,
    title: 'Новое помещение',
    is_open: false,
    scheduling_start: null,
    scheduling_end: null,
    square: 55.0,
    square_kitchen: null,
    square_room: null,
    square_1: null,
    square_2: null,
    square_3: null,
    square_4: null,
    square_5: null,
    power: 15,
    has_gas: false,
    ceil_height: 3.5,
    deep_of_floor: null,
    deleted: false,
    promo_address: 'Улица Мира',
    no_promo: false,
    video_link: null,
    location: {
      id: 3,
      title: 'Торговый центр',
    },
    owner: null,
    owner_busines: null,
    district: {
      id: 13,
      title: 'Петроградский',
      is_center: false,
      is_south: false,
      is_north: true,
    },
    floor: {
      id: 1,
      number: 1,
      title: 'Первый этаж',
    },
    entrance: {
      id: 1,
      title: 'Первая линия',
    },
    format: [
      {
        id: 27,
        title: 'Раньше ничего не было',
      },
    ],
    types: [
      {
        id: 4,
        title: 'Улица',
        only_for_purchase: true,
      },
      {
        id: 14,
        title: 'Витринные окна',
        only_for_purchase: true,
      },
    ],
  },
  {
    id: 10499,
    rent: {
      id: 8872,
      rent_type: {
        id: 2,
        title: 'Долго',
      },
      contact_type: 0,
      title: 'Помещение свободного назначения, 100 м²',
      short_description: 'Сдается помещение свободного назначения.',
      description:
        'Сдается помещение свободного назначения.\nИмеется:\n1. 32 кВт\n2. Два входа (парадный и черный под разгрузку-погрузку)\n3. Большое фасадное остекление\n4. Вентиляция с выходом на крышу.\n5. Зал 50м2 с гостевым туалетом\nпод кафе, производство пиццы, суши и т.Д.\nдоговор на 11 месяцев с дальнейшей с пролонгацией!',
      payback: 0,
      price: 120000,
      price_square: 1200,
      tax: 60000,
      tax_general: 120000,
      promo_address: '',
      no_promo: true,
      exclusive: false,
      status: {
        id: 1,
        title: 'На сайте',
      },
      furniture: {
        id: 2,
        title: 'Нет',
      },
      equipment: {
        id: 2,
        title: 'Нет',
      },
      arendator: null,
      types: [],
    },
    sale: null,
    business_sale: null,
    images: [
      {
        id: 24180,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/4807103443.jpg',
        type: 1,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10499,
      },
    ],
    processed: false,
    object_num: null,
    wcafe: '',
    actual_date: '2018-09-28T05:50:11Z',
    datetime_created: '2018-09-28T05:50:11Z',
    datetime_updated: '2018-09-28T05:50:11Z',
    address_num: null,
    is_supergo: false,
    is_goodview: false,
    district_hidden: false,
    title: 'Кафе',
    is_open: false,
    scheduling_start: null,
    scheduling_end: null,
    square: 100.0,
    square_kitchen: null,
    square_room: null,
    square_1: null,
    square_2: null,
    square_3: null,
    square_4: null,
    square_5: null,
    power: 32,
    has_gas: false,
    ceil_height: 3.2,
    deep_of_floor: null,
    deleted: false,
    promo_address: null,
    no_promo: true,
    video_link: null,
    location: null,
    owner: null,
    owner_busines: null,
    district: {
      id: 17,
      title: 'Фрунзенский',
      is_center: false,
      is_south: true,
      is_north: false,
    },
    floor: {
      id: 1,
      number: 1,
      title: 'Первый этаж',
    },
    entrance: null,
    format: [
      {
        id: 11,
        title: 'Кальянная',
      },
    ],
    types: [
      {
        id: 2,
        title: 'Вытяжка',
        only_for_purchase: true,
      },
      {
        id: 4,
        title: 'Улица',
        only_for_purchase: true,
      },
    ],
  },
]

export const extractArticles = [
  {
    id: 10494,
    rent: {
      id: 8867,
      rent_type: {
        id: 2,
        title: 'Долго',
      },
      contact_type: 0,
      title: 'Помещение свободного назначения, 50 м²',
      short_description:
        'Сдается в аренду отличное помещение в Калининском районе, в 3 минутах ходьбы от Финляндского вокзала и станции метро "Площадь Ленина". Пешеходный переход. Общая площадь 50 кв.М.',
      description:
        'Сдается в аренду отличное помещение в Калининском районе, в 3 минутах ходьбы от Финляндского вокзала и станции метро "Площадь Ленина". Пешеходный переход. Общая площадь 50 кв.М. Помещение расположено на первом этаже, имеет отдельный вход с Лесного проспекта, 4 витринных окна, энергетическая мощность 20 кВт, приточно-вытяжная вентиляция, качественный ремонт, высота потолков 3,5 м. Рядом с помещением Военно -медицинская Академия,крупные банки и бизнес-центры,дворец культуры «Выборгский». \nОтличное место, чтобы открыть: булочки\\ хлеб\\ шаверму\\ суши\\ бургерную и т.Д. \nКолоссальный транспортный и пешеходный трафик. Просмотр в удобное время!',
      payback: 0,
      price: 95000,
      price_square: 1900,
      tax: 47500,
      tax_general: 47500,
      promo_address: '',
      no_promo: true,
      exclusive: false,
      status: {
        id: 1,
        title: 'На сайте',
      },
      furniture: {
        id: 2,
        title: 'Нет',
      },
      equipment: {
        id: 2,
        title: 'Нет',
      },
      arendator: null,
      types: [],
    },
    sale: null,
    business_sale: null,
    images: [
      {
        id: 24148,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/4563641668.jpg',
        type: 1,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10494,
      },
      {
        id: 24149,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/4563641997.jpg',
        type: 1,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10494,
      },
      {
        id: 24150,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/4563642512.jpg',
        type: 1,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10494,
      },
      {
        id: 24147,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/4563643077.jpg',
        type: 0,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10494,
      },
    ],
    processed: false,
    object_num: null,
    wcafe: '',
    actual_date: '2018-09-26T09:57:13Z',
    datetime_created: '2018-09-26T09:57:13Z',
    datetime_updated: '2018-09-26T09:57:13Z',
    address_num: null,
    is_supergo: false,
    is_goodview: false,
    district_hidden: false,
    title: 'Суши Вок',
    is_open: false,
    scheduling_start: null,
    scheduling_end: null,
    square: 50.0,
    square_kitchen: null,
    square_room: null,
    square_1: null,
    square_2: null,
    square_3: null,
    square_4: null,
    square_5: null,
    power: 20,
    has_gas: false,
    ceil_height: 3.5,
    deep_of_floor: null,
    deleted: false,
    promo_address: null,
    no_promo: true,
    video_link: null,
    location: {
      id: 4,
      title: 'ОСЗ',
    },
    owner: null,
    owner_busines: null,
    district: {
      id: 4,
      title: 'Калининский',
      is_center: false,
      is_south: false,
      is_north: true,
    },
    floor: {
      id: 1,
      number: 1,
      title: 'Первый этаж',
    },
    entrance: null,
    format: [
      {
        id: 2,
        title: 'Кафе',
      },
      {
        id: 3,
        title: 'Ресторан',
      },
      {
        id: 4,
        title: 'Столовая',
      },
      {
        id: 5,
        title: 'Фаст-Фуд',
      },
    ],
    types: [
      {
        id: 4,
        title: 'Улица',
        only_for_purchase: true,
      },
    ],
  },
]

export const muzicArticles = [
  {
    id: 10496,
    rent: {
      id: 8868,
      rent_type: {
        id: 2,
        title: 'Долго',
      },
      contact_type: 0,
      title: 'Аренда помещения в Центральном районе',
      short_description: 'Первый этаж\nБольшие окна\nОтличный трафик',
      description:
        'Аренда помещения в Центральном районе на отличном трафике  \nПомещение с хорошей планировкой\nВдоль фасада идут большие окна\nПомещение имеет отдельный вход с улицы и выход во двор\nРанее располагалась торговля\nОбщая площадь - 190 м2, потолки - 3.6 метра\nПодведены все необходимые коммуникации\nВыделенная электрическая мощность - 45 кВт\nВозможна установка приточно-вытяжной вентиляции\nС арендатором заключается долгосрочный договор\n\nАрендная ставка - 500 000 рублей\nКоммунальные услуги оплачиваются отдельно\nКомиссия - 250 000 рублей',
      payback: 0,
      price: 500000,
      price_square: 2631,
      tax: 250000,
      tax_general: 250000,
      promo_address: '',
      no_promo: true,
      exclusive: false,
      status: {
        id: 1,
        title: 'На сайте',
      },
      furniture: {
        id: 2,
        title: 'Нет',
      },
      equipment: {
        id: 2,
        title: 'Нет',
      },
      arendator: null,
      types: [],
    },
    sale: null,
    business_sale: null,
    images: [
      {
        id: 24158,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/fasad_B4t0NQG.jpg',
        type: 1,
        hidden: false,
        is_rent: false,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10496,
      },
      {
        id: 24208,
        position: null,
        image:
          'http://api.worldcafe.ru/media/photo/glweizvgeskh2s5fhlhxx6jpwhgtrafj.jpg',
        type: 0,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10496,
      },
      {
        id: 24209,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/1222112211.jpg',
        type: 0,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10496,
      },
      {
        id: 24210,
        position: null,
        image:
          'http://api.worldcafe.ru/media/photo/32583088_7XPeqvONFDRPJCmUK2Xu_2xUP9-XFY_9kUWA2y0mLOw.jpg',
        type: 0,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10496,
      },
    ],
    processed: true,
    object_num: null,
    wcafe: '',
    actual_date: '2018-10-01T16:57:03Z',
    datetime_created: '2018-09-26T13:43:26Z',
    datetime_updated: '2018-10-01T16:57:03Z',
    address_num: '22',
    is_supergo: false,
    is_goodview: false,
    district_hidden: false,
    title: 'Аптека Радуга',
    is_open: false,
    scheduling_start: null,
    scheduling_end: null,
    square: 190.0,
    square_kitchen: null,
    square_room: null,
    square_1: null,
    square_2: null,
    square_3: null,
    square_4: null,
    square_5: null,
    power: 45,
    has_gas: false,
    ceil_height: 3.6,
    deep_of_floor: null,
    deleted: false,
    promo_address: 'улица Маяковского, д.19/15',
    no_promo: false,
    video_link: null,
    location: {
      id: 3,
      title: 'Торговый центр',
    },
    owner: null,
    owner_busines: null,
    district: {
      id: 18,
      title: 'Центральный',
      is_center: true,
      is_south: false,
      is_north: false,
    },
    floor: {
      id: 1,
      number: 1,
      title: 'Первый этаж',
    },
    entrance: null,
    format: [
      {
        id: 13,
        title: 'Торговое помещение',
      },
    ],
    types: [
      {
        id: 4,
        title: 'Улица',
        only_for_purchase: true,
      },
      {
        id: 14,
        title: 'Витринные окна',
        only_for_purchase: true,
      },
    ],
  },
]

export const elecArticles = [
  {
    id: 10497,
    rent: {
      id: 8869,
      rent_type: {
        id: 2,
        title: 'Долго',
      },
      contact_type: 0,
      title: 'Кафе на оживленной трассе у бензоколонки Shell',
      short_description:
        'Кафе на оживленной трассе у бензоколонки Shell по дороге на Игору',
      description:
        'Предлагается в аренду кафе, расположенное на 11-м километре Новоприозерского шоссе, рядом с заправкой Shell, на пересечении оживленных трасс, в непосредственной близости от транспортной развязки.\n<br/><br/>\nВокруг несколько новых элитных коттеджных поселков. Огромный автомобильный трафик, в том числе и туристический (дорога на Игору).\n<br/><br/>\nОтдельно-стоящее здание. Хороший ремонт. Своя скважина, бойлеры. Приличный контингент. Без оборудования и мебели.\n<br/><br/>\nАрендная ставка 50 000 руб./мес. \n<br/><br/>\nУсловия обсуждаются.\n<br/><br/>\nКомиссия 50 000 руб.',
      payback: 0,
      price: 50000,
      price_square: 625,
      tax: 50000,
      tax_general: 100000,
      promo_address: '11 км Новоприозерское шоссе',
      no_promo: false,
      exclusive: false,
      status: {
        id: 1,
        title: 'На сайте',
      },
      furniture: {
        id: 2,
        title: 'Нет',
      },
      equipment: {
        id: 2,
        title: 'Нет',
      },
      arendator: null,
      types: [],
    },
    sale: null,
    business_sale: null,
    images: [
      {
        id: 24166,
        position: null,
        image:
          'http://api.worldcafe.ru/media/photo/6a255ead-0bd8-469d-85d7-13ba2f180ed4_niH2Juj.jpg',
        type: 1,
        hidden: false,
        is_rent: false,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10497,
      },
      {
        id: 24167,
        position: null,
        image:
          'http://api.worldcafe.ru/media/photo/60a3c6a0-94d9-4cbe-83bb-ddc8a55adb30_Q13gCSy.jpg',
        type: 1,
        hidden: false,
        is_rent: false,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10497,
      },
      {
        id: 24160,
        position: null,
        image:
          'http://api.worldcafe.ru/media/photo/5adb89c9-926e-4d48-91ac-9699733acacf.jpg',
        type: 0,
        hidden: false,
        is_rent: false,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10497,
      },
      {
        id: 24162,
        position: null,
        image:
          'http://api.worldcafe.ru/media/photo/36b05cfb-cccc-4360-988e-78e25d73fe1c.jpg',
        type: 0,
        hidden: false,
        is_rent: false,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10497,
      },
      {
        id: 24164,
        position: null,
        image:
          'http://api.worldcafe.ru/media/photo/904f9b35-8010-4e79-8d0a-e25e943c441f.jpg',
        type: 0,
        hidden: false,
        is_rent: false,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10497,
      },
      {
        id: 24165,
        position: null,
        image:
          'http://api.worldcafe.ru/media/photo/5a20a3e4-98b7-4649-a57e-85543fb17735.jpg',
        type: 0,
        hidden: false,
        is_rent: false,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10497,
      },
    ],
    processed: false,
    object_num: null,
    wcafe: '',
    actual_date: '2018-09-26T15:24:57Z',
    datetime_created: '2018-09-26T14:44:46Z',
    datetime_updated: '2018-09-26T15:24:57Z',
    address_num: null,
    is_supergo: false,
    is_goodview: false,
    district_hidden: false,
    title: 'Придорожное кафе',
    is_open: false,
    scheduling_start: null,
    scheduling_end: null,
    square: 80.0,
    square_kitchen: null,
    square_room: null,
    square_1: null,
    square_2: null,
    square_3: null,
    square_4: null,
    square_5: null,
    power: 30,
    has_gas: false,
    ceil_height: null,
    deep_of_floor: null,
    deleted: false,
    promo_address: 'Новоприозерское шоссе 11-й километр',
    no_promo: false,
    video_link: null,
    location: {
      id: 4,
      title: 'ОСЗ',
    },
    owner: {
      id: 4831,
      email: '',
      phone: '+79112195558',
      first_name: 'Игорь',
      last_name: '',
      patronim: '',
      info: 'Whatsapp по этому номеру',
      company: '',
      image: null,
    },
    owner_busines: null,
    district: {
      id: 19,
      title: 'Всеволожский',
      is_center: false,
      is_south: false,
      is_north: true,
    },
    floor: {
      id: 1,
      number: 1,
      title: 'Первый этаж',
    },
    entrance: {
      id: 1,
      title: 'Первая линия',
    },
    format: [
      {
        id: 2,
        title: 'Кафе',
      },
    ],
    types: [
      {
        id: 2,
        title: 'Вытяжка',
        only_for_purchase: true,
      },
      {
        id: 3,
        title: 'Громкая музыка ночью',
        only_for_purchase: true,
      },
      {
        id: 4,
        title: 'Улица',
        only_for_purchase: true,
      },
      {
        id: 5,
        title: 'ОСЗ',
        only_for_purchase: true,
      },
      {
        id: 14,
        title: 'Витринные окна',
        only_for_purchase: true,
      },
    ],
  },
]

export const furnitureArticles = [
  {
    id: 10498,
    rent: {
      id: 8870,
      rent_type: {
        id: 2,
        title: 'Долго',
      },
      contact_type: 0,
      title: 'Помещение свободного назначения, 55 м²',
      short_description:
        'Помещение 55м2. Сделан хороший ремонт. Мощность 15 квт . Вход с ул. Котовского . Витринные',
      description:
        'Помещение 55м2. Сделан хороший ремонт. Мощность 15 квт . Вход с ул. Котовского . Витринные. Подойдет под любой вид деятельности.',
      payback: 0,
      price: 82500,
      price_square: 1500,
      tax: 41250,
      tax_general: 82500,
      promo_address: 'Улица Мира',
      no_promo: false,
      exclusive: false,
      status: {
        id: 1,
        title: 'На сайте',
      },
      furniture: {
        id: 2,
        title: 'Нет',
      },
      equipment: {
        id: 2,
        title: 'Нет',
      },
      arendator: null,
      types: [],
    },
    sale: null,
    business_sale: null,
    images: [
      {
        id: 24170,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/1ism.jpg',
        type: 1,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10498,
      },
      {
        id: 24171,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/2ism.jpg',
        type: 1,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10498,
      },
      {
        id: 24168,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/4807136074.jpg',
        type: 0,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10498,
      },
      {
        id: 24169,
        position: null,
        image: 'http://api.worldcafe.ru/media/photo/4807136899.jpg',
        type: 0,
        hidden: false,
        is_rent: true,
        is_sale: false,
        is_business_sale: false,
        image_url: null,
        object: 10498,
      },
    ],
    processed: false,
    object_num: null,
    wcafe: '',
    actual_date: '2018-09-27T08:34:33Z',
    datetime_created: '2018-09-27T08:34:33Z',
    datetime_updated: '2018-09-27T08:34:33Z',
    address_num: null,
    is_supergo: false,
    is_goodview: false,
    district_hidden: false,
    title: 'Новое помещение',
    is_open: false,
    scheduling_start: null,
    scheduling_end: null,
    square: 55.0,
    square_kitchen: null,
    square_room: null,
    square_1: null,
    square_2: null,
    square_3: null,
    square_4: null,
    square_5: null,
    power: 15,
    has_gas: false,
    ceil_height: 3.5,
    deep_of_floor: null,
    deleted: false,
    promo_address: 'Улица Мира',
    no_promo: false,
    video_link: null,
    location: {
      id: 3,
      title: 'Торговый центр',
    },
    owner: null,
    owner_busines: null,
    district: {
      id: 13,
      title: 'Петроградский',
      is_center: false,
      is_south: false,
      is_north: true,
    },
    floor: {
      id: 1,
      number: 1,
      title: 'Первый этаж',
    },
    entrance: {
      id: 1,
      title: 'Первая линия',
    },
    format: [
      {
        id: 27,
        title: 'Раньше ничего не было',
      },
    ],
    types: [
      {
        id: 4,
        title: 'Улица',
        only_for_purchase: true,
      },
      {
        id: 14,
        title: 'Витринные окна',
        only_for_purchase: true,
      },
    ],
  },
]
