export const GET_DATA_REQUEST = 'GET_DATA_REQUEST'
export type GET_DATA_REQUEST = typeof GET_DATA_REQUEST

export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS'
export type GET_DATA_SUCCESS = typeof GET_DATA_SUCCESS

export const LOAD_NEW_REQUEST = 'LOAD_NEW_REQUEST'
export type LOAD_NEW_REQUEST = typeof LOAD_NEW_REQUEST

export const LOAD_NEW_SUCCESS = 'LOAD_NEW_SUCCESS'
export type LOAD_NEW_SUCCESS = typeof LOAD_NEW_SUCCESS
